### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by AliennCheng** [steveli/misgan#2]
Hi,

I tried to run the code in my own environment with pytorch 1.6.0.
However, an error occurred as following.
Since I am not familiar with pytorch, I have no idea how to fix it.
Can you help me out?

Error occurred at **block 14** in notebook. Here is the error message.

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-15-a3ac07bc7415> in <module>
>      47 
>      48             mask_loss = -mask_critic(fake_mask).mean()
> ---> 49             (mask_loss + data_loss * alpha).backward()
>      50             mask_gen_optimizer.step()
>      51 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\torch\tensor.py in backward(self, gradient, retain_graph, create_graph)
>     196                 products. Defaults to ``False``.
>     197         """
> --> 198         torch.autograd.backward(self, gradient, retain_graph, create_graph)
>     199 
>     200     def register_hook(self, hook):
> 
> C:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
>      98     Variable._execution_engine.run_backward(
>      99         tensors, grad_tensors, retain_graph, create_graph,
> --> 100         allow_unreachable=True)  # allow_unreachable flag
>     101 
>     102 
>
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [64, 1, 8, 8]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Then, I tried to follow the suggestion torch.autograd.set_detect_anomaly(True) and got this message.
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [64, 1, 8, 8]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by steveli** [comment]
Hi. It seems that the improved variable version tracking introduced in [pytorch 1.2](https://github.com/pytorch/pytorch/releases/tag/v1.2.0) breaks the current implementation. I've updated the requirements file to exclude pytorch 1.2 or up. Please downgrade the installed pytorch and torchvision module according to the updated [requirements](https://github.com/steveli/misgan/blob/master/requirements.txt) file and see if it works for you.

**Comment by AliennCheng** [comment]
Thank you for your reply.
For some reason, it didn't seem to work even if I downgrade to pytorch 1.2, 1.1, 1.0, or even 0.4.1. I am not sure if I did anything wrong.
But I fixed my problem by the function **detach()**.
Now my code is as follow and it seems to work without error messages.
I am not sure if it breaks the logic, though. Please check the correctness. Thanks.

```
data_loss_d = data_loss.detach()
mask_loss = -mask_critic(fake_mask).mean()
(mask_loss + data_loss_d * alpha).backward()
mask_gen_optimizer.step()
```

**Comment by steveli** [comment]
Hi. Your fix unfortunately is not correct as both the data generator (`data_gen`) and the mask generator (`mask_gen`) will not be trained as backpropagation is blocked by `detach()`.

I just tried it on a freshly created virtual environment with `torch==1.1.0 torchvision==0.3.0` and it seemed to work fine. It also runs fine on [Google Colab](https://colab.research.google.com/drive/1oPokD4Jr6YaYEK9T1ipuR2iDzNN0Pe1e?usp=sharing). Do you mind giving it another try on a fresh conda environment (or virtual environment)?

**Comment by steveli** [comment]
Hi. I've tried to migrate the code to the latest release of pytorch (1.6.0). They are now under the directory [src-torch1.6](https://github.com/steveli/misgan/tree/master/src-torch1.6). The only modified files are
- misgan.py
- misgan_impute.py
- misgan.ipynb

Note that [pytorch 1.5](https://github.com/pytorch/pytorch/releases/tag/v1.5.0) has changed the behavior of the Adam optimizer, which we use for training. The current hyperparameters that was tuned for pytroch 1.1.0 might give you slightly different results. In some rare cases you might need to tune the hyperparameters a bit.

**Comment by AliennCheng** [comment]
I am using pytorch 1.6.0 and the code under src-torch1.6 works fine now.
Thank you very much for your kindly help.
